name:                 HOS
version:              0.1.0.0
visibility:           public
id:                   HOS-0.1.0.0-LhliF75o34eIqMz4MUSLTu
key:                  HOS-0.1.0.0-LhliF75o34eIqMz4MUSLTu
abi:                  e512c400d7658eddaf6342fd95fba132
exposed:              True
exposed-modules:      HOS HOS.Data HOS.Dual HOS.ExampleLib
import-dirs:
    /Users/taniguchiakane/HOS/.stack-work/install/x86_64-osx/fe004d4292793ccdc3f7d9ca513bde66cafb35a09e491c1612ca6bb9e03ce004/9.10.3/lib/x86_64-osx-ghc-9.10.3-5528/HOS-0.1.0.0-LhliF75o34eIqMz4MUSLTu

library-dirs:
    /Users/taniguchiakane/HOS/.stack-work/install/x86_64-osx/fe004d4292793ccdc3f7d9ca513bde66cafb35a09e491c1612ca6bb9e03ce004/9.10.3/lib/x86_64-osx-ghc-9.10.3-5528/HOS-0.1.0.0-LhliF75o34eIqMz4MUSLTu

library-dirs-static:
    /Users/taniguchiakane/HOS/.stack-work/install/x86_64-osx/fe004d4292793ccdc3f7d9ca513bde66cafb35a09e491c1612ca6bb9e03ce004/9.10.3/lib/x86_64-osx-ghc-9.10.3-5528/HOS-0.1.0.0-LhliF75o34eIqMz4MUSLTu

dynamic-library-dirs:
    /Users/taniguchiakane/HOS/.stack-work/install/x86_64-osx/fe004d4292793ccdc3f7d9ca513bde66cafb35a09e491c1612ca6bb9e03ce004/9.10.3/lib/x86_64-osx-ghc-9.10.3-5528

data-dir:
    /Users/taniguchiakane/HOS/.stack-work/install/x86_64-osx/fe004d4292793ccdc3f7d9ca513bde66cafb35a09e491c1612ca6bb9e03ce004/9.10.3/share/x86_64-osx-ghc-9.10.3-5528/HOS-0.1.0.0

hs-libraries:         HSHOS-0.1.0.0-LhliF75o34eIqMz4MUSLTu
depends:
    base-4.20.2.0-21f0 containers-0.7-645c
    criterion-1.6.4.0-DoyHSBLDiu9EBqnPBupLi9
    free-5.2-JTiaWHq1OtqC83ZGv05IUa
    log-domain-0.13.2-BK3a3AoLA79JzgHBBrMj0w mtl-2.3.1-254a
    mwc-random-0.15.3.0-JMRxJu5QHFZ8hjGPGgD2uA
    random-1.2.1.3-ExseuoPUPMc3SeYRvn9ZB7
    statistics-0.16.5.0-9eF0fiF8QObJv5L7xUrbF4
    transformers-0.6.1.1-c68e vector-0.13.2.0-K8pmR5PeaEhEE3IjTDIylm

haddock-interfaces:
    /Users/taniguchiakane/HOS/.stack-work/install/x86_64-osx/fe004d4292793ccdc3f7d9ca513bde66cafb35a09e491c1612ca6bb9e03ce004/9.10.3/doc/HOS-0.1.0.0/HOS.haddock

haddock-html:
    /Users/taniguchiakane/HOS/.stack-work/install/x86_64-osx/fe004d4292793ccdc3f7d9ca513bde66cafb35a09e491c1612ca6bb9e03ce004/9.10.3/doc/HOS-0.1.0.0
